In [2]:
import pandas as pd 

df1 = pd.DataFrame({
    '반': ['1', '1', '2', '2', '3', '3'],
    '이름': ['대한', '민국', '우리', '나라', '만세', '하늘'],
    '수학': [90, 80, 85, 90, 100, 55],
    '영어': [80, 75, 70, 80, 88, 60],
    '국어': [85, 90, 95, 75, 90, 80]
})

df

   반  이름   수학  영어  국어
0  1  대한   90  80  85
1  1  민국   80  75  90
2  2  우리   85  70  95
3  2  나라   90  80  75
4  3  만세  100  88  90
5  3  하늘   55  60  80

In [10]:
import pandas as pd 

df2 = pd.DataFrame({
    '반': ['1', '1', '2', '2', '3', '1'],
    '이름': ['대한', '민국', '우리', '나라', '만세', '민국'],
    '수학': [90, 80, 85, 90, 100, 80],
    '영어': [80, 75, 70, 80, 88, 75],
    '국어': [85, 90, 95, 75, 90, 90]
})

df2

   반  이름   수학  영어  국어
0  1  대한   90  80  85
1  1  민국   80  75  90
2  2  우리   85  70  95
3  2  나라   90  80  75
4  3  만세  100  88  90
5  1  민국   80  75  90

In [13]:
df2.drop_duplicates()

   반  이름   수학  영어  국어
0  1  대한   90  80  85
1  1  민국   80  75  90
2  2  우리   85  70  95
3  2  나라   90  80  75
4  3  만세  100  88  90